name: Build and Test Spring Boot Application

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # or 'corretto'
          java-version: 24

      - name: Build with Maven
        run: mvn clean package

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t somnath1150/springboot-container-application .

      - name: Push Docker image
        run: docker push somnath1150/springboot-container-application

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Automate test case using bruno CLI
        run: bru run --env local --reporter-html results.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.html

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-container-application
          path: target/*.jar
